# To install the git pre-commit hook run:
#   pre-commit install
default_language_version:
  python: python3.9

repos:
  # pre-commit-hooks supplies a multitude of small hooks
  # To get an overview of them all as well as the ones used here, please see
  # https://github.com/pre-commit/pre-commit-hooks#hooks-available
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: end-of-file-fixer
    - id: debug-statements
    - id: check-yaml
      name: Check YAML
    - id: check-toml
      name: Check TOML
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]

  # pyupgrade is a tool for automatically upgrading Python syntax for newer versions of
  # the language
  # It works on files in-place
  - repo: https://github.com/asottile/pyupgrade
    # Latest version for Python 3.7: 3.3.2
    # Latest version for Python 3.8: 3.8.0
    rev: v3.17.0
    hooks:
    - id: pyupgrade
      args: [--py37-plus]

  # Black is a code style and formatter
  # It works on files in-place
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    - id: black

  # ruff is a Python linter, incl. import sorter and formatter
  # It works partly on files in-place
  # More information can be found in its documentation:
  # https://docs.astral.sh/ruff/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
    - id: ruff
      # Fix what can be fixed in-place and exit with non-zero status if files were
      # changed and/or there are rules violations.
      args:
      - "--fix"
      - "--exit-non-zero-on-fix"
      - "--show-fixes"
      - "--no-unsafe-fixes"

  # Bandit is a security linter
  # More information can be found in its documentation:
  # https://bandit.readthedocs.io/en/latest/
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
    - id: bandit
      args: ["-r"]
      exclude: ^tests/.*$

  # mypy is a static typing linter
  # The main code repository can be found at:
  # https://github.com/python/mypy
  # The project's documentation can be found at:
  # https://mypy.readthedocs.io/en/stable/index.html
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
    - id: mypy

  - repo: https://github.com/SINTEF/ci-cd
    rev: v2.8.2
    hooks:
    - id: docs-api-reference
      args:
      - "--package-dir=ci_cd"
