name: CI/CD - New updates to 'main'

on:
  push:
    branches: [main]

jobs:
  updated-main:
    name: Call reusable workflow
    if: github.repository_owner == 'SINTEF'
    uses: ./.github/workflows/ci_cd_updated_default_branch.yml
    with:
      git_username: "TEAM 4.0[bot]"
      git_email: "TEAM4.0@SINTEF.no"
      permanent_dependencies_branch: "ci/dependency-updates"
      default_repo_branch: main
      update_docs: true
      doc_extras: "[docs]"
      update_python_api_ref: false
      update_docs_landing_page: false
      changelog_exclude_tags_regex: "^v[0-9]+$"
      test: false
    secrets:
      PAT: ${{ secrets.RELEASE_PAT }}
