name: CI - Check pyproject.toml dependencies

on:
  workflow_call:
    inputs:
      git_username:
        description: "A git username (used to set the 'user.name' config option)."
        required: true
        type: string
      git_email:
        description: "A git user's email address (used to set the 'user.email' config option)."
        required: true
        type: string
      permanent_dependencies_branch:
        description: "The branch name for the permanent dependency updates branch."
        required: false
        type: string
        default: "ci/dependency-updates"
      python_version:
        description: "The Python version to use for the workflow."
        required: false
        type: string
        default: "3.9"
      install_extras:
        description: "Any extras to install from the local repository through 'pip'. Must be encapsulated in square parentheses (`[]`) and be separated by commas (`,`) without any spaces. Example: `'[dev,release]'`."
        required: false
        type: string
        default: ""
      pr_body_file:
        description: "Relative path to PR body file from the root of the repository. Example: `'.github/utils/pr_body_deps_check.txt'`."
        required: false
        type: string
        default: ""
      fail_fast:
        description: "Whether the task to update dependencies should fail if any error occurs."
        required: false
        type: boolean
        default: false
      pr_labels:
        description: "A comma separated list of strings of GitHub labels to use for the created PR."
        required: false
        type: string
        default: ""
      ignore:
        description: "Create ignore conditions for certain dependencies. A multi-line string of ignore rules, where each line is an ellipsis-separated (`...`) string of key/value-pairs. One line per dependency. This option is similar to the `ignore` option of Dependabot."
        required: false
        type: string
        default: ""
      branch_name_extension:
        description: "A string to append to the branch name of the created PR. Example: `'-my-branch'`. It will be appended after a forward slash, so the final branch name will be `ci/update-pyproject/-my-branch`."
        required: false
        type: string
        default: ""
      debug:
        description: "Whether to run the workflow in debug mode, printing extra debug information."
        required: false
        type: boolean
        default: false
    secrets:
      PAT:
        description: "A personal access token (PAT) with rights to update the `permanent_dependencies_branch`. This will fallback on `GITHUB_TOKEN`."
        required: false

jobs:
  check-dependencies:
    name: Check & update dependencies in `pyproject.toml`
    runs-on: ubuntu-latest

    steps:
    - name: Checkout permanent dependencies branch in ${{ github.repository }}
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.permanent_dependencies_branch }}
        fetch-depth: 0

    - name: Set up Python ${{ inputs.python_version }}
      uses: actions/setup-python@v4
      with:
        python-version: "${{ inputs.python_version }}"

    - name: Install Python dependencies
      run: |
        if [ "${{ inputs.debug }}" == "true" ]; then
          set -x
          VERBOSE=-vvv
        else
          VERBOSE=
        fi

        python -m pip install -U ${VERBOSE} pip
        pip install -U ${VERBOSE} setuptools wheel
        pip install ${VERBOSE} .${{ inputs.install_extras }}
        pip install ${VERBOSE} git+https://github.com/SINTEF/ci-cd.git@v2.5.2

    - name: Set up git user
      run: |
        if [ "${{ inputs.debug }}" == "true" ]; then
          set -x
        fi

        git config --global user.name "${{ inputs.git_username }}"
        git config --global user.email "${{ inputs.git_email }}"

    - name: Run ci-cd task
      run: |
        if [ "${{ inputs.debug }}" == "true" ]; then
          set -x
          VERBOSE=--verbose
        else
          VERBOSE=
        fi

        if [ "${{ inputs.fail_fast }}" == "true" ]; then
          FAIL_FAST=--fail-fast
        else
          FAIL_FAST=
        fi

        IGNORE_OPTIONS=()
        while IFS= read -r line; do
          if [ -n "${line}" ]; then IGNORE_OPTIONS+=(--ignore="${line}"); fi
        done <<< "${{ inputs.ignore }}"

        ci-cd update-deps ${FAIL_FAST} ${VERBOSE} \
          --root-repo-path="${PWD}" \
          --ignore-separator="..." \
          "${IGNORE_OPTIONS[@]}"

        if [ "${{ inputs.debug }}" == "true" ]; then
          git status
        fi

        if [ -n "$(git status --porcelain pyproject.toml)" ]; then
          echo "UPDATE_DEPS=true" >> $GITHUB_ENV
          git add pyproject.toml
          git commit -m "Update dependencies in \`pyproject.toml\`"
        else
          echo "UPDATE_DEPS=false" >> $GITHUB_ENV
        fi

    - name: Set PR body
      if: env.UPDATE_DEPS == 'true'
      run: |
        if [ "${{ inputs.debug }}" == "true" ]; then
          set -x
        fi

        if [ -z "${{ inputs.pr_body_file }}" ] || [ ! -f "${{ inputs.pr_body_file }}" ]; then
          PR_BODY_FILE=.tmp_pr-body_${{ github.run_id }}_${{ github.run_number }}_${{ github.run_attempt }}.txt
          echo "PR_BODY_FILE=${PR_BODY_FILE}" >> $GITHUB_ENV

          echo -e "### Update dependencies (\`pyproject.toml\`)\n\nAutomatically created PR based on the ['CI - Check pyproject.toml dependencies' workflow](https://SINTEF.github.io/ci-cd/latest/workflows/ci_check_pyproject_dependencies/) in [SINTEF/ci-cd](https://github.com/SINTEF/ci-cd)." > ${PR_BODY_FILE}
          echo "Using default PR body."
          echo "REMOVE_PR_BODY_FILE=true" >> $GITHUB_ENV
        else
          echo "Using found PR body text file at ${{ inputs.pr_body_file }}."
          echo "PR_BODY_FILE=${{ inputs.pr_body_file }}" >> $GITHUB_ENV
          echo "REMOVE_PR_BODY_FILE=false" >> $GITHUB_ENV
        fi

    - name: Fetch PR body
      if: env.UPDATE_DEPS == 'true'
      id: pr_body
      uses: chuhlomin/render-template@v1.8
      with:
        template: ${{ env.PR_BODY_FILE }}

    - name: Remove temporary file
      if: env.REMOVE_PR_BODY_FILE == 'true'
      run: rm -f ${{ env.PR_BODY_FILE }}

    - name: Create PR
      if: env.UPDATE_DEPS == 'true'
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
        committer: "${{ inputs.git_username }} <${{ inputs.git_email }}>"
        author: "${{ inputs.git_username }} <${{ inputs.git_email }}>"
        branch: ci/update-pyproject${{ inputs.branch_name_extension && format('/{0}', inputs.branch_name_extension) || ''}}
        delete-branch: true
        title: "[Auto-generated] Check & update dependencies (`pyproject.toml`)"
        body: ${{ steps.pr_body.outputs.result }}
        labels: "${{ inputs.pr_labels }}"

    - name: Information
      run: 'echo "${{ steps.cpr.outputs.pull-request-operation }} PR #${{ steps.cpr.outputs.pull-request-number }}: ${{ steps.cpr.outputs.pull-request-url }}"'
